### ISSUE TITLE
It takes so long to use GPU for training: still 0 epoch after a day.

### ISSUE THREAD

**Issue by DaehanKim** [bdhingra/ga-reader#1]
```
->  python run.py
Using gpu device 0: TITAN X (Pascal) (CNMeM is disabled, cuDNN 5105)
/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
loading vocabularies from data/wdw/vocab.txt ...
vocab_size = 324613
num characters = 102
0 anonymoused entities
324613 other tokens (including @placeholder, @begin and @end)
preparing training data ...
@placeholder not found in  data/wdw/training/AFP_ENG_20040114.0037.question . Fixing...
@placeholder not found in  data/wdw/training/CNA_ENG_19990325.0027.question . Fixing...
@placeholder not found in  data/wdw/training/AFP_ENG_20020701.0566.question . Fixing...
preparing validation data ...
preparing test data ...
building minibatch loaders ...
building network ...
167991/324613 vocabs are initialized with word2vec embeddings.
WARNING (theano.tensor.blas): We did not found a dynamic library into the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
training ...
loading previously saved model
...
Epoch 0 TRAIN loss=8.4052e-01 acc=0.7188 elapsed=75252.5
Epoch 0 TRAIN loss=4.3968e-01 acc=0.8438 elapsed=75258.4
Epoch 0 TRAIN loss=1.0990e+00 acc=0.5312 elapsed=75271.3
Epoch 0 TRAIN loss=7.4241e-01 acc=0.5625 elapsed=75279.6
```

It uses only a portion of TITAN X, such as 300~400MB, while it has two TITAN X of 12GB each.
I tried `libgpuarray` but it is too complicated to follow up. I actually did everything its instruction says but can't figure out how I can apply `libgpuarray` to individual projects I need. Is there any `.rc` file needed? Any help will be much appreciated! Thank you in advance.

**Comment by bdhingra** [comment]
Hi, on my single Titan X it takes slightly more than 2 hours per epoch, so there seems to be some issue with your environment. I have never used `libgpuarray` so can't help with that.

Have you tried looking into the following warning? Maybe this is what is causing the slowdown:
```
WARNING (theano.tensor.blas): We did not found a dynamic library into the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
```

**Comment by DaehanKim** [comment]
thanks it helped! Now I got no such error but another one : 
```
->  python run.py 
Using gpu device 0: TITAN X (Pascal) (CNMeM is disabled, cuDNN 5105)
/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
loading vocabularies from data/wdw/vocab.txt ...
vocab_size = 324613
num characters = 102
0 anonymoused entities
324613 other tokens (including @placeholder, @begin and @end)
preparing training data ...
@placeholder not found in  data/wdw/training/AFP_ENG_20040114.0037.question . Fixing...
@placeholder not found in  data/wdw/training/CNA_ENG_19990325.0027.question . Fixing...
@placeholder not found in  data/wdw/training/AFP_ENG_20020701.0566.question . Fixing...
preparing validation data ...
preparing test data ...
building minibatch loaders ...
building network ...
167991/324613 vocabs are initialized with word2vec embeddings.
training ...
loading previously saved model
Traceback (most recent call last):
  File "run.py", line 42, in <module>
    train.main(save_path, params)
  File "/home/dhpark/projects/ga-reader-master/ga-reader-master/train.py", line 49, in main
    m.load_model('%s/best_model.p'%save_path)
  File "/home/dhpark/projects/ga-reader-master/ga-reader-master/model/GAReader.py", line 201, in load_model
    L.set_all_param_values(self.network, data)
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/helper.py", line 517, in set_all_param_values
    p.set_value(v)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/var.py", line 154, in set_value
    self.container.value = value  # this will copy a numpy ndarray
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 466, in __set__
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/type.py", line 125, in filter_inplace
    data)
TypeError: ('CudaNdarrayType(float32, matrix), with dtype float32, cannot store a value of dtype float64 without risking loss of precision.If you do not mind, please cast your data to float32.', array([[  1.76229179e-02,   4.80884191e-04,   2.29197880e-03, ...,
         -2.98576476e-03,   9.51279234e-03,   3.82327964e-03],
       [  1.03511603e-03,   4.08328092e-03,   1.12536373e-02, ...,
         -1.68731343e-02,  -5.69001911e-03,  -7.35614216e-03],
       [ -4.66563548e-02,   2.25832075e-02,  -2.91766354e-02, ...,
         -4.03881372e-02,   2.09967715e-02,  -3.10920747e-02],
       ..., 
       [ -5.01903661e-02,  -2.74159377e-05,   8.17719757e-02, ...,
         -1.21030236e-01,  -1.82318264e-02,  -1.06254772e-01],
       [  5.78189670e-02,  -7.25256724e-02,   6.89241232e-02, ...,
          9.64543511e-02,   5.27208662e-02,   1.02383120e-01],
       [  2.97515955e-02,  -2.59640580e-02,   8.76134930e-02, ...,
          1.05353108e-01,   6.83907476e-02,   3.34386360e-02]]), 'Container name "None"')
```
I thought it came from word2vecglove.txt so I searched it but it was not the case.
I think it is this part : 
```
# Check if data.dtype can be accurately cast to self.dtype
            if isinstance(data, numpy.ndarray):
                up_dtype = scal.upcast(self.dtype, data.dtype)
                if up_dtype == self.dtype:
                    return cuda.filter(data, self.broadcastable,
                                       strict, old_data)
                else:
                    raise TypeError(
                        '%s, with dtype %s, cannot store a value of '
                        'dtype %s without risking loss of precision.'
                        'If you do not mind, please cast your data to %s.'
                        % (self, self.dtype, data.dtype, self.dtype),
                        data)
```
Have you ever seen this issue? By the way, your previous reply helped a lot.. thank you!

**Comment by bdhingra** [comment]
Can you try building a new model from scratch? Right now it is loading a previously saved model from the `experiments/` directory. 

To make it build a new model, delete or move the existing models from the `experiments/` directory. 

Also make sure that you run with the following flag: `floatX=float32`. You can either add this to `~/.theanorc` file, or prefix `THEANO_FLAGS=floatX=float32` to the python command you run.

**Comment by DaehanKim** [comment]
I deleted things in experiments/ and ran it again and I found it working!
Thank you so much!!

The problem was previous model.... Have a good day!

```
Epoch 1 TRAIN loss=9.6479e-01 acc=0.6562 elapsed=21767.1
Epoch 1 TRAIN loss=6.8325e-01 acc=0.7812 elapsed=21769.0
Epoch 1 TRAIN loss=5.0005e-01 acc=0.8125 elapsed=21772.1
Epoch 1 TRAIN loss=6.8601e-01 acc=0.6875 elapsed=21774.0
Epoch 1 TRAIN loss=6.2223e-01 acc=0.7188 elapsed=21775.2
Epoch 1 TRAIN loss=6.4578e-01 acc=0.6562 elapsed=21777.9
Epoch 1 TRAIN loss=6.9038e-01 acc=0.6875 elapsed=21779.1
Epoch 1 TRAIN loss=6.2486e-01 acc=0.7188 elapsed=21781.1
After Epoch 1: Train acc=0.7188, Val acc=0.6828
Epoch 2 TRAIN loss=6.0996e-01 acc=0.6875 elapsed=1.9
Epoch 2 TRAIN loss=7.0140e-01 acc=0.6250 elapsed=3.8
Epoch 2 TRAIN loss=7.9496e-01 acc=0.5938 elapsed=5.3
Epoch 2 TRAIN loss=7.0636e-01 acc=0.6562 elapsed=8.0
Epoch 2 TRAIN loss=4.9333e-01 acc=0.7500 elapsed=9.8
Epoch 2 TRAIN loss=5.5875e-01 acc=0.7812 elapsed=10.9
Epoch 2 VAL loss=7.3803e-01 acc=0.6884 max_acc=0.6884
Epoch 2 TRAIN loss=1.3197e+00 acc=0.4062 elapsed=304.4

```

**Comment by Xuweijia-buaa** [comment]
I have the same problem as you, and I want to know how do you fix this problem finally?I tried many ways including disable cpu throttling,reboot my os and compile lapack and ATLAS library, but it makes my running even slower...It has taken more than 3 hours just to prepare training data, and I don't know when will it start to run the first epoch or whether the warning will occur. Maybe my way of solving it have some problems, so I really want to know how do you fix it?
